Feature/html structure
AnnaKadomtseva/cat-energy pull request #1
Opened 2019-04-05 18:03 UTC by AnnaKadomtseva

Сделала html структуру страниц: главная, каталог и форма

2019-04-08 07:10 UTC, 0ro requested changes

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +        <img class="page-header__logo-image" src="#" width="" height="" alt="Логотип Cat Energy">
Для чего здесь пустые атрибуты width и heigth? src с # тоже выглядит странно, я как правило сразу вставляю путь к изображению. Тем более, что ты уже нарезала изображения

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +      <a class="page-header__logo" href="index.html">
имеет смысл примиксовать класс logo сюда

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +            <li class="site-list__item site-list__item">
double class

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +            <h3 class="catalog-list__title catalog-list__title--plus">
Для чего здесь нужен модификатор?

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +      <section class="page-catalog__action action-present">
Почему section?

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +      <section class="page-footer__contacts contacts">
Здесь тоже неясен смысл этого тэга

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +      <section class="page-footer__social social">
И здесь

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +      <section class="page-footer__copyright copyright">
И здесь

2019-04-08 07:10 UTC, 0ro commented on source/form.html
> +              <a>Главная</a>
Почему без href?

2019-04-08 07:10 UTC, 0ro commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Для чего здесь visually-hidden?

2019-04-08 07:10 UTC, 0ro commented on source/img/icon-fb.svg
> +<?xml version="1.0" encoding="utf-8"?>
Изображения уже были подготовлены? или ты сама их вырезала?

2019-04-08 07:10 UTC, 0ro commented on source/catalog.html
> +        <b class="contacts__invitation">Приглашаем к сотрудничеству дилеров!</b>
Почему тэг b?

2019-04-08 07:12 UTC, 0ro commented
Также хотелось бы, что commit messages были на английском языке.

2019-04-09 14:48 UTC, AnnaKadomtseva commented on source/catalog.html
> +      <a class="page-header__logo" href="index.html">
То есть задать два класса page-header__logo и logo?

2019-04-09 14:51 UTC, 0ro commented on source/catalog.html
> +      <a class="page-header__logo" href="index.html">
Да, выделить logo в отдельный блок

2019-04-09 14:53 UTC, AnnaKadomtseva commented on source/catalog.html
> +        <img class="page-header__logo-image" src="#" width="" height="" alt="Логотип Cat Energy">
Делаю по аналогии с прошлым интенсивом. #-заглушки. а пустые атрибуты заполню когда пройду соответствующую лекцию о размерах и изображениях. Диман нашел на гитхабе у какого то парня этот проект кэт энерджи в общем доступе, как он проходил  интенсив, им на начальном этапе дали все изображения, я скачала их оттуда..

2019-04-09 14:54 UTC, AnnaKadomtseva commented on source/catalog.html
> +            <li class="site-list__item site-list__item">
косяк, исправлю

2019-04-09 14:56 UTC, AnnaKadomtseva commented on source/catalog.html
> +            <h3 class="catalog-list__title catalog-list__title--plus">
чтобы вставить значок "плюс"(на макете увидела), если это изображение вообще, я не знаю как надо верстать эту карточку товаров

2019-04-09 14:56 UTC, 0ro commented on source/catalog.html
> +        <img class="page-header__logo-image" src="#" width="" height="" alt="Логотип Cat Energy">
Ок, делай как удобнее

2019-04-09 14:59 UTC, AnnaKadomtseva commented on source/catalog.html
> +        <b class="contacts__invitation">Приглашаем к сотрудничеству дилеров!</b>
Когда не знаю какой тег поставить, то можно b или span-чик...здесь надо поставить обычный <p>?

2019-04-09 15:00 UTC, AnnaKadomtseva commented on source/form.html
> +              <a>Главная</a>
Забыла, исправлю

2019-04-09 15:14 UTC, AnnaKadomtseva commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Даже не знаю можно ли тегу <legend> давать класс visually-hidden, по смыслу тут два блока: один заполнить контактные данные, другой-радиокнопки и подписи у них нет, как например у следующих Контактные данные (владельца кота), Комментарий...поэтому я дала название смысловое и скрыла его. Как правильно не знаю.

2019-04-09 15:18 UTC, AnnaKadomtseva commented on source/img/icon-fb.svg
> +<?xml version="1.0" encoding="utf-8"?>
Скачала у другого человека

2019-04-09 15:25 UTC, 0ro commented on source/catalog.html
> +        <b class="contacts__invitation">Приглашаем к сотрудничеству дилеров!</b>
Лучше span для такого

2019-04-10 07:45 UTC, 0ro requested changes

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +            <a class="catalog-list__button" href="#">Заказать</a>
На каждой из страниц есть одинаковые зеленые кнопки. Такие вещи выносятся в отдельный блок. Т.е. тебе нужно для всех похожих кнопок добавить класс button, или btn, или b-btn, или еще как то. Это позволит переиспользовать блок там где ты захочешь.

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +            <a class="catalog-list__button" href="#">Заказать</a>
Тоже самое касается полей ввода и всего того, что хоть где то повторяется визуально. Нужно активно использовать принцип DRY. Don't repeat yourself. Это значит, что ты не должна повторять себя, т.е. писать один и тот же код дважды

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +            <h3 class="catalog-list__title catalog-list__title--plus">
Я бы сверстал примерно вот так:
```html
 <li class="card catalog-list__item">
  <div class="card__header">
    <a href="#">
      <img src="" alt="" class="card__preview">
    </a>
  </div>
  <div class="card__content">
    <h3 class="card__title"></h3>
    <div class="card__description">
      <table class="table">
        <tr>
          <td></td>
          <td></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="card__footer">
    <button class="btn btn--success">Заказать</button>
  </div>
</li>
<li class="card card--gray catalog-list__item">
  <div class="card__header">
    <a href="#">
      <i class="icon icon--large icon--plus"></i>
    </a>
  </div>
  <div class="card__content">
    <h3 class="card__title"></h3>
    <div class="card__description">
      <p></p>
    </div>
  </div>
  <div class="card__footer">
    <button class="btn btn--default">Показать все</button>
  </div>
</li>
```
Но я не претендую на истину. Это только мое мнение. Твой подход имеет большую связность. Т.е. нельзя переиспользовать таблицу, нельзя будет переиспользовать кнопки. И изменение содержимого блока приводит к большим изменениям

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +          <table class="extra-list__info">
может здесь стоит сделать блок table, а для этой таблицы добавить модификатор table--horizontal?

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +              <td class="extra-list__button"><a href="#">Заказать</a></td>
блок button

2019-04-10 07:45 UTC, 0ro commented on source/catalog.html
> +    <footer class="page-footer">
Этот блок нужно полностью переверстать. Возможно стоит обсудить голосом.

2019-04-10 07:45 UTC, 0ro commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Вас так учили? это для чего нужно?

2019-04-10 17:22 UTC, AnnaKadomtseva commented on source/catalog.html
> +            <h3 class="catalog-list__title catalog-list__title--plus">
Я в любом случае выберу твой вариант, так как у меня очень маленький опыт в написании кода и я не знаю многих вещей. Мой подход это больше плод моего воображения

2019-04-10 17:28 UTC, AnnaKadomtseva commented on source/catalog.html
> +            <h3 class="catalog-list__title catalog-list__title--plus">
Только <tr> надеюсь можно 3 штуки сделать, так как у меня в таблице 3 строчки?

2019-04-10 17:30 UTC, AnnaKadomtseva commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Нас конкретно этому случаю не учили, просто увидела похожий и так сделала. А можно ли fieldset использовать без legend? тогда и скрывать ничего не надо

2019-04-10 17:33 UTC, AnnaKadomtseva commented on source/catalog.html
> +          <table class="extra-list__info">
Да, так и сделаю

2019-04-11 11:24 UTC, 0ro commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Использовать fieldset без legend вполне допустимо. Валидатор ругаться на это не будет. Но тогда зачем вообще нужен именно fieldset? Я не являюсь специалистом по доступности и семантике сайтов, но возможно именно такое комбо из скрытого legend и fieldset что то да дает в этом плане, в этом и был мой вопрос, возможно вам об этом рассказывали что то на лекциях. Поэтому тебе нужно узнать, для чего так делают? А если причин нет, то почему не использовать div?

2019-04-11 17:42 UTC, AnnaKadomtseva commented on source/form.html
> +            <legend class="visually-hidden">Анкета кота</legend>
Сделала так по аналогии с моим техномартом, а его по аналогии с учебным барбершопом. На курсах учили, что не надо много div-ов использовать, если есть много других смысловых тегов. Но! Давай сделаем этот сайт как ты бы его сделал..мне сейчас важно разобраться что и как верстать, вникнуть в это. Я прошла первый интенсив, и это капля в море из того, что еще надо узнать.

2019-04-15 14:51 UTC, 0ro requested changes

2019-04-15 14:51 UTC, 0ro commented on source/form.html
> +        <div class="page-header__logo">
Нужно сделать page-header__logo, в котором будет лежать два элемента, с двумя частями логотипа (изображение кота и cat energy)

2019-04-15 14:51 UTC, 0ro commented on source/form.html
> +          <fieldset class="profile-list__cat-profile form-item form-item--cat-info">
form-item--cat-info плохое название для модификатора. Получается, что ты создала блок form-item, который ничего не знает о котах, но ему ты повесила модификатор с котом. Получается, что этот модификатор у тебя будет на один раз. А что если изменить содержимое этого блока на не котов, а на собак? Ты привязалась к контексту сильно. В таких случаях лучше использовать более абстрактные названия.

2019-04-15 15:13 UTC, AnnaKadomtseva commented on source/form.html
> +          <fieldset class="profile-list__cat-profile form-item form-item--cat-info">
form-item--pet-info норм?

2019-04-15 15:17 UTC, AnnaKadomtseva commented on source/form.html
> +        <div class="page-header__logo">
Аа, вроде поняла

2019-04-16 14:33 UTC, 0ro requested changes

2019-04-16 14:33 UTC, 0ro commented on source/form.html
> +            <div class="form-control__field-wrap">
Здесь и ниже должен быть form-control вместо form-control__field-wrap

2019-04-16 14:33 UTC, 0ro commented on source/form.html
> +          <fieldset class="profile-list__group form-control">
здесь нужно удалить form-control

2019-04-16 14:33 UTC, 0ro commented on source/form.html
> +          <fieldset class="profile-list__group form-control">
здесь убрать нужно form-control

2019-04-16 14:33 UTC, 0ro commented on source/form.html
> +            <ul class="form-control__list form-check">
Здесь убрать ul и li внутри, это не список, а группа radio buttons. Не стоит из этого городить целый блок с элементами

2019-04-16 14:33 UTC, 0ro commented on source/form.html
> +            <ul class="form-control__list form-check">
Я бы сделал примерно так. Это все схематично и я не стал верстать все, но это должно быть все примерно так:
```html
  <main class="programm-selection">
    <h1 class="program-selection__title">
      Подбор программы
    </h1>
    <div class="program-selection__description">
      Заполните анкету и мы подберем...
    </div>
    <div class="program-selection__content">
      <section class="form-section">
        <h3 class="form-section__header visually-hidden"></h3>
        <div class="form-section__content">
          <div class="form-section__item">
            <div class="form-control">
              <label class="form-control__label"></label>
              <input type="text" class="form-control__input">
            </div>
            <div class="form-control">
              <label class="form-control__label"></label>
              <input type="text" class="form-control__input">
            </div>
            <div class="form-control">
              <label class="form-control__label"></label>
              <input type="text" class="form-control__input">
            </div>
          </div>
          <div class="form-section__item">
            <div class="form-group form-group--outlined">
              <div class="form-control">
                <label class="form-control__label"></label>
                <input type="radio" class="form-control__input">
              </div>
              <div class="form-control">
                <label class="form-control__label"></label>
                <input type="radio" class="form-control__input">
              </div>
              <div class="form-control">
                <label class="form-control__label"></label>
                <input type="radio" class="form-control__input">
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="form-section">
        <h3 class="form-section__header"></h3>
        <div class="form-section__content">

        </div>
      </section>
      <section class="form-section">
        <h3 class="form-section__header"></h3>
        <div class="form-section__content">
          
        </div>
      </section>
      <section class="form-section">
        <h3 class="form-section__header"></h3>
        <div class="form-section__content">
          
        </div>
      </section>
    </div>
  </main>
```

2019-04-17 19:08 UTC, AnnaKadomtseva commented on source/form.html
> +            <ul class="form-control__list form-check">
<main class="program-selection">
      <h1 class="program-selection__title">Подбор программы</h1>
      <div class="program-selection__description">
        Заполните анкету и мы подберем программу питания для вашего кота
      </div>
      <form  class="program-selection__form" action="https://echo.htmlacademy.ru" method="post">
        <div class="program-selection__content">
          <section class="form-section">
            <h3 class="form-section__header visually-hidden">Данные о вашем питомце</h3>
            <div class="form-section__content">
              <div class="form-section__item">
                <div class="form-control">
                  <label class="form-control__label" for="cat-login">Имя:<sup>*</sup></label>
                  <input class="form-control__input" type="text" id="cat-login" name="login" placeholder="Барсик">
                </div>
                <div class="form-control">
                  <label class="form-control__label" for="cat-weight">Вес (кг):<sup>*</sup></label>
                  <input class="form-control__input" id="cat-weight" type="number" name="weight" placeholder="7">
                </div>
                <div class="form-control">
                  <label class="form-control__label" for="cat-age">Возраст (лет):<sup>*</sup></label>
                  <input class="form-control__input" id="cat-age" type="number" name="age" placeholder="7">
                </div>
              </div>
              <div class="form-section__item">
                <div class="form-group form-group--outlined">
                  <div class="form-control">
                    <label class="form-control__label" for="filter-losing">Похудение</label>
                    <input class="form-control__input" id="filter-losing" type="radio" name="group" value="losing" checked>
                  </div>
                  <div class="form-control">
                    <label class="form-control__label" for="filter-weight-gain">Набор массы</label>
                    <input class="form-control__input" id="filter-weight-gain" type="radio" name="group" value="weight-gain">
                  </div>
                  <div class="form-control">
                    <label class="form-control__label" for="filter-advice">Не знаю (нужен ваш совет)</label>
                    <input class="form-control__input" id="filter-advice" type="radio" name="group" value="advice">
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section class="form-section">
            <h3 class="form-section__header">Контактные данные (владельца кота)</h3>
            <div class="form-section__content">
              <div class="form-section__item">
                <div class="form-control">
                  <label class="form-control__label" for="user-email">E-mail:<sup>*</sup></label>
                  <input class="form-control__input" id="user-email" type="email" name="emailaddress" placeholder="kuklachev@gmail.com">
                  <span class="form-control__icon"></span>
                </div>
                <div class="form-control">
                  <label class="form-control__label" for="user-tel">Телефон:<sup>*</sup></label>
                  <input class="form-control__input" id="user-tel" type="tel" name="tel" placeholder="8(960)900-60-90">
                  <span class="form-control__icon"></span>
                </div>
              </div>
            </div>
          </section>
          <section class="form-section">
            <h3 class="form-section__header">Комментарий</h3>
            <div class="form-section__content">
              <div class="form-section__item">
                <div class="form-control">
                  <textarea class="form-control__input" name="text" rows="5" cols="30" placeholder="Расскажите обо всех повадках кота"></textarea>
                </div>
              </div>
            </div>
          </section>
          <section class="form-section">
            <h3 class="form-section__header">Дополнительно</h3>
            <div class="form-section__content">
              <div class="form-section__item">
                <div class="form-group form-group--outlined">
                  <div class="form-control">
                    <label class="form-control__label" for="filter-sugar">Сахарозаменитель</label>
                    <input class="form-control__input" type="checkbox" name="products" value="sugar" id="filter-sugar" checked>
                  </div>
                  <div class="form-control">
                    <label class="form-control__label" for="filter-water">Питьевая вода</label>
                    <input class="form-control__input" type="checkbox" name="products" value="water" id="filter-water">
                  </div>
                  <div class="form-control">
                    <label class="form-control__label" for="filter-milk">Молоко</label>
                    <input class="form-control__input" type="checkbox" name="products" value="milk" id="filter-milk">
                  </div>
                  <div class="form-control">
                    <label class="form-control__label" for="filter-vitamin">Витамины</label>
                    <input class="form-control__input" type="checkbox" name="products" value="vitamin" id="filter-vitamin">
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <div class="program-selection__footer">
          <button class="program-selection__button btn" type="submit">Отправить заявку</button>
          <p class="program-selection__note"><sup>*</sup> — Обязательные поля</p>
        </div>
      </form>
    </main>

2019-04-18 13:23 UTC, 0ro approved these changes

2019-04-18 13:57 UTC, merged