Created styles for block page-header
AnnaKadomtseva/cat-energy pull request #2
Opened 2019-04-23 16:53 UTC by AnnaKadomtseva

2019-04-24 09:06 UTC, 0ro requested changes

2019-04-24 09:06 UTC, 0ro commented on source/sass/global/scaffolding.scss
> +input[type="radio"].visually-hidden {
Без инпутов не работало?

2019-04-24 09:06 UTC, 0ro commented on source/sass/global/scaffolding.scss
> +  background-color: #ffffff;
В переменную цвет вынести. И использовать #fff

2019-04-24 09:06 UTC, 0ro commented on source/sass/global/vars.scss
> +$black: #000000;
#000

2019-04-24 09:06 UTC, 0ro commented on source/sass/global/fonts.scss
> +}
Добавляй пустую строку в конце файла

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/index/header-info.scss
> +  z-index: -1;
Здесь не нужен z-index

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/site-list.scss
> +  font-family: $oswald;
Для того, чтобы изменить вес шрифта не нужно писать еще раз font-family

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/index/header-info.scss
> +  z-index: -1;
При увеличении размера экрана котик остается на месте, а справа добавляется белая полоса. Нужно придумать другой способ верстки этого блока

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  width: 320px;
Почему фиксированная ширина?

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  padding-right: 20px;
для такого лучше писать один padding

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  display: flex;
Для всех флексовых свойств нужны префиксы

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  margin-left: 50px;
При увеличении размера экрана позиция будет зафиксирована, а блок должен быть всегда посередине

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  margin-left: -20px;
Лучше из page-header убрать боковые паддинги и перенести их туда где они нужны, для того чтобы не писать отрицательный margin

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  min-width: 360px;
Почему такое число?

2019-04-24 09:06 UTC, 0ro commented on source/sass/blocks/common/logo.scss
> +  width: 200px;
width и height нужно убрать, а расстояение между элеметами через margin или еще как то

2019-04-25 06:47 UTC, AnnaKadomtseva commented on source/sass/global/scaffolding.scss
> +input[type="radio"].visually-hidden {
Как я поняла это набор стандартных стилей для класса visually-hidden. Нашла в лекциях, вставила к себе. Возможно и без импутов будет работать.

2019-04-25 06:47 UTC, AnnaKadomtseva commented on source/sass/global/scaffolding.scss
> +  background-color: #ffffff;
Ок

2019-04-25 06:49 UTC, AnnaKadomtseva commented on source/sass/global/vars.scss
> +$black: #000000;
Ок, такая запись из 3-х знаков подходит только для черного и белого цветов? Если например цвет, где все 6 цифр имеют разные значения, то нужно записывать все 6? К примеру -  #12ca45

2019-04-25 06:52 UTC, AnnaKadomtseva commented on source/sass/global/fonts.scss
> +}
То есть 28 строка будет пустой? Или где..

2019-04-25 06:56 UTC, AnnaKadomtseva commented on source/sass/blocks/common/site-list.scss
> +  font-family: $oswald;
Удалить font-family: $oswald, оставить только font-weight

2019-04-25 06:57 UTC, AnnaKadomtseva commented on source/sass/blocks/common/page-header.scss
> +  padding-right: 20px;
Пока так пишу чтобы не путаться в сторонах..

2019-04-25 06:58 UTC, AnnaKadomtseva commented on source/sass/blocks/common/page-header.scss
> +  display: flex;
Можно в самом конце прогнать через автопрефиксер?

2019-04-25 07:00 UTC, 0ro commented on source/sass/global/vars.scss
> +$black: #000000;
Такая запись подходит для всех повторяющихся дважды символов подряд. Например:
#cceecc => #cec
#bbccee => #bce
#887711 => #871

2019-04-25 07:01 UTC, 0ro commented on source/sass/global/fonts.scss
> +}
Да, послденяя строка должна быть пустой

2019-04-25 07:02 UTC, AnnaKadomtseva commented on source/sass/blocks/common/page-header.scss
> +  margin-left: -20px;
Прописала page-header боковые паддинги , чтобы контент не прилипал к краям экрана. Куда их лучше прописать? в какой-то контейнер в котором будут лежать все блоки?

2019-04-25 07:02 UTC, 0ro commented on source/sass/blocks/common/page-header.scss
> +  display: flex;
Лучше прикрутить автопрефиксер сразу в gulp. Посмотри как его прикрутить в gulp
https://www.npmjs.com/package/gulp-autoprefixer

2019-04-25 07:02 UTC, AnnaKadomtseva commented on source/sass/blocks/common/page-header.scss
> +  min-width: 360px;
320 +паддинги 20+20 = 360

2019-05-15 06:29 UTC, 0ro requested changes

2019-05-15 06:29 UTC, 0ro commented on source/sass/blocks/index/program-opportunity.scss
> +  padding: 0 20px 20px 20px;
0 20px 20px

2019-05-15 06:29 UTC, 0ro commented on source/sass/blocks/index/program-card.scss
> +  background-color: $grey;
Давай здесь добавим position relative

2019-05-15 06:29 UTC, 0ro commented on source/sass/blocks/index/program-card.scss
> +  position: relative;
здесь absolute и выставь позицию в соответсвии с макетом

2019-05-15 06:29 UTC, 0ro commented on source/sass/blocks/index/program-card.scss
> +  text-align: center;
добавь левый padding, чтобы оставить место под иконку

2019-05-15 06:29 UTC, 0ro commented on source/sass/blocks/index/program-card.scss
> +  left: 100px;
Может лучше right: 0?

2019-05-15 06:33 UTC, 0ro commented on source/sass/blocks/index/advantages-list.scss
> +  background-color: $green;
вынеси все повторяющиеся стили в advantages-list__item:before, а в модификаторах только background-image оставь. Очень много копипаста получается

2019-05-15 16:20 UTC, AnnaKadomtseva commented on source/sass/blocks/index/advantages-list.scss
> +  background-color: $green;
это будет миксин @mixin ?

2019-05-15 16:23 UTC, 0ro commented on source/sass/blocks/index/advantages-list.scss
> +  background-color: $green;
Нет, .advantages-list__item:before это просто селектор внутри которого будут эти стили

2019-05-15 16:35 UTC, AnnaKadomtseva commented on source/sass/blocks/index/program-card.scss
> +  left: 100px;
При  right: 0 стрелка находится на самом тексте. если только -35px поставить..

2019-05-15 16:37 UTC, 0ro commented on source/sass/blocks/index/program-card.scss
> +  left: 100px;
Лучше -35px поставить, потому что ширина текста может быть разной, а ширина стрелки одинакова

2019-05-15 16:38 UTC, AnnaKadomtseva commented on source/sass/blocks/index/program-card.scss
> +  left: 100px;
хорошо, поняла

2019-05-15 16:39 UTC, AnnaKadomtseva commented on source/sass/blocks/index/advantages-list.scss
> +  background-color: $green;
до меня дошло, когда я коммент оставила

2019-05-22 07:38 UTC, 0ro commented on source/sass/blocks/common/toggle.scss
> +.toggle--open::before {
выбери или open или opened, и сделай так:
```css
.toggle--open {
  &:before {
    ...
  }
  &:after {
    ...
  }
}
```
и везде где это возможно используй возможность вложенности стилей

2019-05-22 07:38 UTC, 0ro commented on source/sass/blocks/common/main-nav.scss
> +  width: 100%;
сюда display: none перенеси

2019-05-22 07:38 UTC, 0ro approved these changes

2019-05-22 17:51 UTC, merged